# Generated by Django 5.2.4 on 2025-08-06 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_number', models.CharField(blank=True, max_length=50)),
                ('license_states', models.JSONField(blank=True, default=list)),
                ('specializations', models.JSONField(blank=True, default=list)),
                ('years_experience', models.IntegerField(blank=True, null=True)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('preferred_databases', models.JSONField(blank=True, default=list)),
                ('default_search_strategy', models.CharField(blank=True, max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_mode', models.BooleanField(default=False)),
                ('compact_view', models.BooleanField(default=False)),
                ('auto_save', models.BooleanField(default=True)),
                ('keyboard_shortcuts', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('project_updates', models.BooleanField(default=True)),
                ('deadline_alerts', models.BooleanField(default=True)),
                ('team_mentions', models.BooleanField(default=True)),
                ('marketing_emails', models.BooleanField(default=False)),
                ('weekly_digest', models.BooleanField(default=True)),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('organization', 'Organization Only'), ('private', 'Private')], default='organization', max_length=20)),
                ('activity_tracking', models.BooleanField(default=True)),
                ('data_sharing', models.BooleanField(default=False)),
                ('analytics_opt_in', models.BooleanField(default=True)),
                ('working_hours_start', models.TimeField(default='09:00')),
                ('working_hours_end', models.TimeField(default='17:00')),
                ('break_reminders', models.BooleanField(default=False)),
                ('focus_mode', models.BooleanField(default=False)),
                ('attorney_settings', models.JSONField(blank=True, default=dict)),
                ('analyst_settings', models.JSONField(blank=True, default=dict)),
                ('admin_settings', models.JSONField(blank=True, default=dict)),
                ('client_settings', models.JSONField(blank=True, default=dict)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('session_timeout', models.IntegerField(default=480)),
                ('auto_logout', models.BooleanField(default=True)),
                ('login_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
                'db_table': 'user_settings',
            },
        ),
    ]
