# Generated by Django 5.2.4 on 2025-08-06 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_usersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowUserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_role', models.CharField(choices=[('workflow_admin', 'Workflow Admin'), ('workflow_manager', 'Workflow Manager'), ('step_owner', 'Step Owner'), ('quality_reviewer', 'Quality Reviewer'), ('observer', 'Observer')], default='observer', max_length=50)),
                ('can_create_templates', models.BooleanField(default=False, verbose_name='Create Templates')),
                ('can_edit_templates', models.BooleanField(default=False, verbose_name='Edit Templates')),
                ('can_delete_templates', models.BooleanField(default=False, verbose_name='Delete Templates')),
                ('can_activate_templates', models.BooleanField(default=False, verbose_name='Activate Templates')),
                ('can_view_templates', models.BooleanField(default=True, verbose_name='View Templates')),
                ('can_create_workflows', models.BooleanField(default=False, verbose_name='Create Workflows')),
                ('can_start_workflows', models.BooleanField(default=False, verbose_name='Start Workflows')),
                ('can_pause_workflows', models.BooleanField(default=False, verbose_name='Pause Workflows')),
                ('can_resume_workflows', models.BooleanField(default=False, verbose_name='Resume Workflows')),
                ('can_cancel_workflows', models.BooleanField(default=False, verbose_name='Cancel Workflows')),
                ('can_delete_workflows', models.BooleanField(default=False, verbose_name='Delete Workflows')),
                ('can_assign_workflows', models.BooleanField(default=False, verbose_name='Assign Workflows')),
                ('can_view_workflows', models.BooleanField(default=True, verbose_name='View Workflows')),
                ('can_execute_steps', models.BooleanField(default=False, verbose_name='Execute Steps')),
                ('can_complete_steps', models.BooleanField(default=False, verbose_name='Complete Steps')),
                ('can_skip_steps', models.BooleanField(default=False, verbose_name='Skip Steps')),
                ('can_reassign_steps', models.BooleanField(default=False, verbose_name='Reassign Steps')),
                ('can_view_steps', models.BooleanField(default=True, verbose_name='View Steps')),
                ('can_approve_quality', models.BooleanField(default=False, verbose_name='Approve Quality')),
                ('can_reject_quality', models.BooleanField(default=False, verbose_name='Reject Quality')),
                ('can_override_quality', models.BooleanField(default=False, verbose_name='Override Quality')),
                ('can_view_quality', models.BooleanField(default=True, verbose_name='View Quality')),
                ('can_manage_roles', models.BooleanField(default=False, verbose_name='Manage Roles')),
                ('can_view_analytics', models.BooleanField(default=False, verbose_name='View Analytics')),
                ('can_manage_system', models.BooleanField(default=False, verbose_name='Manage System')),
                ('can_add_comments', models.BooleanField(default=True, verbose_name='Add Comments')),
                ('can_view_comments', models.BooleanField(default=True, verbose_name='View Comments')),
                ('can_mention_users', models.BooleanField(default=True, verbose_name='Mention Users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow Permission',
                'verbose_name_plural': 'Workflow Permissions',
                'db_table': 'workflow_user_permissions',
            },
        ),
    ]
