# Generated by Django 5.2.4 on 2025-08-07 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_workflow_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataConfigurationPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_mapping_rules', models.BooleanField(default=False, verbose_name='View Column Mapping Rules')),
                ('can_create_mapping_rules', models.BooleanField(default=False, verbose_name='Create Column Mapping Rules')),
                ('can_edit_mapping_rules', models.BooleanField(default=False, verbose_name='Edit Column Mapping Rules')),
                ('can_delete_mapping_rules', models.BooleanField(default=False, verbose_name='Delete Column Mapping Rules')),
                ('can_activate_mapping_rules', models.BooleanField(default=False, verbose_name='Activate/Deactivate Mapping Rules')),
                ('can_import_export_rules', models.BooleanField(default=False, verbose_name='Import/Export Mapping Rules')),
                ('can_view_dataset_mappings', models.BooleanField(default=False, verbose_name='View Dataset Mappings')),
                ('can_edit_dataset_mappings', models.BooleanField(default=False, verbose_name='Edit Dataset Mappings')),
                ('can_approve_mappings', models.BooleanField(default=False, verbose_name='Approve Mapping Suggestions')),
                ('can_reject_mappings', models.BooleanField(default=False, verbose_name='Reject Mapping Suggestions')),
                ('can_bulk_manage_mappings', models.BooleanField(default=False, verbose_name='Bulk Manage Mappings')),
                ('can_view_dynamic_fields', models.BooleanField(default=False, verbose_name='View Dynamic Fields Registry')),
                ('can_create_dynamic_fields', models.BooleanField(default=False, verbose_name='Create Dynamic Fields')),
                ('can_edit_dynamic_fields', models.BooleanField(default=False, verbose_name='Edit Dynamic Fields')),
                ('can_delete_dynamic_fields', models.BooleanField(default=False, verbose_name='Delete Dynamic Fields')),
                ('can_migrate_fields', models.BooleanField(default=False, verbose_name='Migrate Dynamic Fields')),
                ('can_archive_fields', models.BooleanField(default=False, verbose_name='Archive Dynamic Fields')),
                ('can_manage_field_types', models.BooleanField(default=False, verbose_name='Manage Field Types')),
                ('can_view_mapping_analytics', models.BooleanField(default=False, verbose_name='View Mapping Analytics')),
                ('can_configure_auto_mapping', models.BooleanField(default=False, verbose_name='Configure Auto-mapping Settings')),
                ('can_manage_migration_system', models.BooleanField(default=False, verbose_name='Manage Migration System')),
                ('can_backup_restore_config', models.BooleanField(default=False, verbose_name='Backup/Restore Configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_configuration_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Configuration Permission',
                'verbose_name_plural': 'Data Configuration Permissions',
                'db_table': 'data_configuration_permissions',
            },
        ),
    ]
