# Generated by Django 5.2.4 on 2025-10-22 19:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_data_configuration_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('role_permission_update', 'Role Permission Update'), ('user_permission_create', 'User Permission Create'), ('user_permission_update', 'User Permission Update'), ('user_permission_delete', 'User Permission Delete')], help_text='Type of permission change', max_length=50)),
                ('target_role', models.CharField(blank=True, help_text='Role whose permissions were modified', max_length=50, null=True)),
                ('description', models.TextField(help_text='Human-readable description of the change')),
                ('changes', models.JSONField(default=dict, help_text='Detailed change data (added, removed, modified permissions)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user who made the change', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent of the browser used', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(help_text='User who made the permission change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_changes_made', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, help_text='User whose permissions were modified', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_changes_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permission Audit Log',
                'verbose_name_plural': 'Permission Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='accounts_pe_created_8ddfcd_idx'), models.Index(fields=['actor'], name='accounts_pe_actor_i_19b614_idx'), models.Index(fields=['target_user'], name='accounts_pe_target__e8eb3f_idx'), models.Index(fields=['action'], name='accounts_pe_action_7aa6ff_idx')],
            },
        ),
    ]
