# Generated by Django 5.2.4 on 2025-10-22 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_permissionauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('lead_attorney', 'Lead Attorney'), ('attorney', 'Attorney'), ('paralegal', 'Paralegal'), ('analyst', 'Analyst'), ('client', 'Client'), ('guest', 'Guest')], help_text='Role name (unique)', max_length=50, unique=True)),
                ('permissions', models.JSONField(default=list, help_text='List of permission strings for this role')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated these permissions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_permission_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'db_table': 'role_permissions',
                'ordering': ['role'],
            },
        ),
    ]
