# Generated by Django 5.2.4 on 2025-09-17 06:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prior_art', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('element_text', models.TextField(help_text='Raw element text from claim')),
                ('element_position', models.PositiveIntegerField(help_text='Order in claim')),
                ('primary_feature_type', models.CharField(choices=[('structural', 'Structural Feature'), ('functional', 'Functional Feature'), ('application', 'Application Feature')], help_text='Primary categorization using MECE framework', max_length=20)),
                ('feature_subcategory', models.CharField(blank=True, help_text='Detailed subcategory within primary type', max_length=50)),
                ('categorization_confidence', models.DecimalField(decimal_places=3, help_text='AI confidence score (0.000-1.000)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('structural_keywords', models.JSONField(default=list, help_text='Material, component, dimensional terms - stored as JSON array')),
                ('functional_keywords', models.JSONField(default=list, help_text='Process, operation, behavior terms - stored as JSON array')),
                ('application_keywords', models.JSONField(default=list, help_text='Use-case, environment, integration terms - stored as JSON array')),
                ('legal_synonyms', models.JSONField(default=list, help_text='Legal and technical equivalents - stored as JSON array')),
                ('broader_terms', models.JSONField(default=list, help_text='Broader conceptual terms - stored as JSON array')),
                ('narrower_terms', models.JSONField(default=list, help_text='More specific implementations - stored as JSON array')),
                ('analysis_context', models.JSONField(default=dict, help_text='Additional analysis context and reasoning')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'claim_elements',
            },
        ),
        migrations.CreateModel(
            name='EvidenceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_id', models.CharField(help_text='External reference ID', max_length=100)),
                ('evidence_type', models.CharField(choices=[('patent', 'Patent'), ('published_application', 'Published Application'), ('technical_paper', 'Technical Paper'), ('standard', 'Industry Standard'), ('product_manual', 'Product Manual'), ('website', 'Website/Online Content'), ('expert_declaration', 'Expert Declaration'), ('prior_use', 'Prior Use Evidence'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=500)),
                ('authors_inventors', models.JSONField(default=list, help_text='Authors/inventors - stored as JSON array')),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('jurisdiction', models.CharField(blank=True, max_length=10)),
                ('source_database', models.CharField(blank=True, max_length=50)),
                ('abstract_summary', models.TextField(blank=True)),
                ('key_disclosure', models.TextField(blank=True, help_text='Key technical disclosure')),
                ('relevance_level', models.CharField(choices=[('high', 'High Relevance'), ('medium', 'Medium Relevance'), ('low', 'Low Relevance'), ('not_relevant', 'Not Relevant'), ('under_review', 'Under Review')], default='under_review', max_length=20)),
                ('legal_relevance_score', models.DecimalField(blank=True, decimal_places=2, help_text='Legal relevance score (0-100)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('analysis_status', models.CharField(choices=[('pending', 'Pending Analysis'), ('analyzing', 'Under Analysis'), ('analyzed', 'Analysis Complete'), ('requires_expert', 'Requires Expert Review')], default='pending', max_length=20)),
                ('analysis_notes', models.TextField(blank=True)),
                ('is_relevant', models.BooleanField(default=False, help_text='Selected as relevant evidence')),
                ('is_primary_reference', models.BooleanField(default=False, help_text='Primary reference for invalidity')),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata from source database')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyzed_by', models.ForeignKey(blank=True, help_text='User who performed the analysis', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evidence_items',
            },
        ),
        migrations.CreateModel(
            name='ClaimEvidenceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage_type', models.CharField(choices=[('exact', 'Exact Match'), ('equivalent', 'Equivalent Disclosure'), ('broader', 'Broader Disclosure'), ('narrower', 'Narrower Disclosure'), ('similar', 'Similar Concept'), ('combination', 'Requires Combination')], max_length=20)),
                ('coverage_percentage', models.PositiveSmallIntegerField(help_text='Estimated coverage percentage', validators=[django.core.validators.MaxValueValidator(100)])),
                ('legal_analysis', models.TextField(blank=True, help_text='Legal analysis of coverage')),
                ('confidence_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('covered_elements', models.ManyToManyField(help_text='Specific claim elements covered by this evidence', to='prior_art.claimelement')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prior_art.evidenceitem')),
            ],
            options={
                'db_table': 'claim_evidence_mappings',
            },
        ),
        migrations.CreateModel(
            name='PatentClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_number', models.PositiveIntegerField()),
                ('claim_type', models.CharField(choices=[('independent', 'Independent Claim'), ('dependent', 'Dependent Claim')], max_length=20)),
                ('claim_text', models.TextField(help_text='Complete claim text')),
                ('analysis_status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('completed', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('depends_on_claim', models.ForeignKey(blank=True, help_text='Parent claim for dependent claims', null=True, on_delete=django.db.models.deletion.CASCADE, to='prior_art.patentclaim')),
            ],
            options={
                'db_table': 'patent_claims',
            },
        ),
        migrations.AddField(
            model_name='evidenceitem',
            name='relevant_claims',
            field=models.ManyToManyField(help_text='Claims this evidence is relevant to', through='prior_art.ClaimEvidenceMapping', to='prior_art.patentclaim'),
        ),
        migrations.AddField(
            model_name='claimevidencemapping',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prior_art.patentclaim'),
        ),
        migrations.AddField(
            model_name='claimelement',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='prior_art.patentclaim'),
        ),
        migrations.CreateModel(
            name='PriorArtProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('project_type', models.CharField(choices=[('freedom_to_operate', 'Freedom to Operate'), ('novelty_search', 'Novelty Search'), ('invalidity_search', 'Invalidity Search'), ('landscape_analysis', 'Landscape Analysis'), ('state_of_art', 'State of the Art'), ('custom_search', 'Custom Search')], db_index=True, default='freedom_to_operate', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planning', 'Planning'), ('active', 'Active Research'), ('analysis', 'Analysis Phase'), ('review', 'Review & Validation'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='draft', max_length=50)),
                ('target_patent_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('target_patent_title', models.CharField(blank=True, max_length=500)),
                ('target_jurisdiction', models.CharField(blank=True, max_length=10)),
                ('target_priority_date', models.DateField(blank=True, null=True)),
                ('target_publication_date', models.DateField(blank=True, null=True)),
                ('search_objectives', models.JSONField(default=dict, help_text='Strategic objectives and success criteria')),
                ('geographic_scope', models.JSONField(default=list, help_text='Jurisdictions to search (US, EP, JP, CN, etc.) - stored as JSON array')),
                ('time_scope', models.JSONField(default=dict, help_text='Date ranges and temporal constraints')),
                ('technology_scope', models.JSONField(default=dict, help_text='Technology areas and classification scope')),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0, help_text='Overall project completion percentage', validators=[django.core.validators.MaxValueValidator(100)])),
                ('total_searches', models.PositiveIntegerField(default=0)),
                ('total_results', models.PositiveIntegerField(default=0)),
                ('analyzed_results', models.PositiveIntegerField(default=0)),
                ('selected_references', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('analytics_project', models.ForeignKey(blank=True, help_text='Link to parent analytics project if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prior_art_projects', to='analytics.analyticsproject')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_prior_art_projects', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_prior_art_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prior_art_projects',
            },
        ),
        migrations.AddField(
            model_name='evidenceitem',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='prior_art.priorartproject'),
        ),
        migrations.CreateModel(
            name='PriorArtProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Project Owner'), ('lead_researcher', 'Lead Researcher'), ('researcher', 'Researcher'), ('analyst', 'Legal Analyst'), ('reviewer', 'Reviewer'), ('viewer', 'Viewer')], max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prior_art.priorartproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prior_art_project_memberships',
            },
        ),
        migrations.AddField(
            model_name='priorartproject',
            name='team_members',
            field=models.ManyToManyField(related_name='prior_art_projects', through='prior_art.PriorArtProjectMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PriorArtReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('fto_report', 'Freedom to Operate Report'), ('novelty_report', 'Novelty Assessment Report'), ('invalidity_report', 'Invalidity Analysis Report'), ('landscape_report', 'Technology Landscape Report'), ('claim_chart', 'Claim Chart'), ('evidence_summary', 'Evidence Summary'), ('search_report', 'Search Report'), ('executive_summary', 'Executive Summary')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('report_sections', models.JSONField(default=dict, help_text='Report structure and content sections')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('review', 'Under Review'), ('completed', 'Completed'), ('delivered', 'Delivered')], default='draft', max_length=20)),
                ('generation_progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('file_path', models.FileField(blank=True, upload_to='prior_art_reports/')),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('html', 'HTML')], default='pdf', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('included_evidence', models.ManyToManyField(help_text='Evidence items included in this report', to='prior_art.evidenceitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='prior_art.priorartproject')),
            ],
            options={
                'db_table': 'prior_art_reports',
            },
        ),
        migrations.CreateModel(
            name='SearchSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('search_purpose', models.CharField(choices=[('initial_landscape', 'Initial Landscape'), ('focused_search', 'Focused Search'), ('claim_specific', 'Claim-Specific Search'), ('gap_analysis', 'Gap Analysis'), ('validation', 'Validation Search')], max_length=30)),
                ('search_strategy', models.JSONField(default=dict, help_text='Complete search strategy including keywords, classes, etc.')),
                ('research_query_ids', models.JSONField(default=list, help_text='Linked research query IDs for execution - stored as JSON array')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('execution_log', models.JSONField(default=list, help_text='Detailed execution log')),
                ('search_duration', models.DurationField(blank=True, null=True)),
                ('api_calls_made', models.PositiveIntegerField(default=0)),
                ('databases_searched', models.JSONField(default=list, help_text='Databases searched - stored as JSON array')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_sessions', to='prior_art.priorartproject')),
            ],
            options={
                'db_table': 'search_sessions',
            },
        ),
        migrations.AddField(
            model_name='evidenceitem',
            name='search_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='prior_art.searchsession'),
        ),
        migrations.CreateModel(
            name='TargetPatent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patent_number', models.CharField(db_index=True, max_length=100)),
                ('jurisdiction', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=500)),
                ('inventors', models.JSONField(default=list, help_text='List of inventors - stored as JSON array')),
                ('assignees', models.JSONField(default=list, help_text='List of assignees - stored as JSON array')),
                ('priority_date', models.DateField(blank=True, null=True)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('grant_date', models.DateField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True)),
                ('specification_text', models.TextField(blank=True, help_text='Full patent specification')),
                ('technology_keywords', models.JSONField(default=list, help_text='Technology keywords - stored as JSON array')),
                ('ipc_classifications', models.JSONField(default=list, help_text='IPC classifications - stored as JSON array')),
                ('cpc_classifications', models.JSONField(default=list, help_text='CPC classifications - stored as JSON array')),
                ('analysis_status', models.CharField(choices=[('pending', 'Pending Analysis'), ('analyzing', 'Analyzing'), ('completed', 'Analysis Complete'), ('failed', 'Analysis Failed')], default='pending', max_length=20)),
                ('analysis_summary', models.JSONField(default=dict, help_text='AI-generated patent analysis summary')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='target_patent_analysis', to='prior_art.priorartproject')),
            ],
            options={
                'db_table': 'target_patents',
            },
        ),
        migrations.AddField(
            model_name='patentclaim',
            name='target_patent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='prior_art.targetpatent'),
        ),
        migrations.AlterUniqueTogether(
            name='claimevidencemapping',
            unique_together={('claim', 'evidence')},
        ),
        migrations.AddIndex(
            model_name='claimelement',
            index=models.Index(fields=['claim', 'element_position'], name='claim_eleme_claim_i_beee71_idx'),
        ),
        migrations.AddIndex(
            model_name='claimelement',
            index=models.Index(fields=['primary_feature_type'], name='claim_eleme_primary_dd2425_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='priorartprojectmembership',
            unique_together={('project', 'user')},
        ),
        migrations.AddIndex(
            model_name='priorartproject',
            index=models.Index(fields=['project_type', 'status'], name='prior_art_p_project_e10c73_idx'),
        ),
        migrations.AddIndex(
            model_name='priorartproject',
            index=models.Index(fields=['created_by', 'status'], name='prior_art_p_created_21bae2_idx'),
        ),
        migrations.AddIndex(
            model_name='priorartproject',
            index=models.Index(fields=['created_at'], name='prior_art_p_created_59b668_idx'),
        ),
        migrations.AddIndex(
            model_name='searchsession',
            index=models.Index(fields=['project', 'status'], name='search_sess_project_8f2a84_idx'),
        ),
        migrations.AddIndex(
            model_name='searchsession',
            index=models.Index(fields=['created_at'], name='search_sess_created_fb705b_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenceitem',
            index=models.Index(fields=['project', 'relevance_level'], name='evidence_it_project_f831ca_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenceitem',
            index=models.Index(fields=['evidence_type', 'relevance_level'], name='evidence_it_evidenc_badbeb_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenceitem',
            index=models.Index(fields=['is_relevant', 'is_primary_reference'], name='evidence_it_is_rele_cf8470_idx'),
        ),
        migrations.AddIndex(
            model_name='patentclaim',
            index=models.Index(fields=['target_patent', 'claim_number'], name='patent_clai_target__46dc48_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='patentclaim',
            unique_together={('target_patent', 'claim_number')},
        ),
    ]
