# Generated by Django 5.2.4 on 2025-09-17 04:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_add_data_configuration_permissions'),
        ('prosecution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatentApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('application_number', models.CharField(blank=True, max_length=50, null=True)),
                ('patent_number', models.CharField(blank=True, max_length=50, null=True)),
                ('application_type', models.CharField(choices=[('utility', 'Utility Patent'), ('design', 'Design Patent'), ('plant', 'Plant Patent'), ('provisional', 'Provisional Application'), ('pct', 'PCT Application'), ('continuation', 'Continuation'), ('divisional', 'Divisional'), ('cip', 'Continuation-in-Part')], max_length=20)),
                ('jurisdiction', models.CharField(choices=[('US', 'United States'), ('EP', 'European Patent Office'), ('JP', 'Japan'), ('CN', 'China'), ('KR', 'South Korea'), ('CA', 'Canada'), ('AU', 'Australia'), ('IN', 'India'), ('PCT', 'PCT International')], default='US', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('filed', 'Filed'), ('pending', 'Pending Examination'), ('under_examination', 'Under Examination'), ('office_action', 'Office Action Response Due'), ('allowed', 'Allowed'), ('granted', 'Granted'), ('abandoned', 'Abandoned'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('inventors', models.JSONField(default=list, help_text='List of inventor names')),
                ('assignees', models.JSONField(default=list, help_text='List of assignee names')),
                ('priority_date', models.DateField(blank=True, null=True)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('grant_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True)),
                ('background', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('detailed_description', models.TextField(blank=True)),
                ('technology_area', models.CharField(blank=True, max_length=200)),
                ('ipc_classes', models.JSONField(default=list, help_text='International Patent Classification codes')),
                ('us_classes', models.JSONField(default=list, help_text='US Patent Classification codes')),
                ('keywords', models.JSONField(default=list)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costs_to_date', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estimated_total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_confidential', models.BooleanField(default=True)),
                ('priority_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attorney', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prosecution_cases', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'db_table': 'patent_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfficeAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('non_final', 'Non-Final Office Action'), ('final', 'Final Office Action'), ('restriction', 'Restriction Requirement'), ('advisory', 'Advisory Action'), ('notice_allowance', 'Notice of Allowance'), ('notice_abandonment', 'Notice of Abandonment')], max_length=20)),
                ('mailing_date', models.DateField()),
                ('response_due_date', models.DateField()),
                ('examiner_name', models.CharField(blank=True, max_length=100)),
                ('examiner_phone', models.CharField(blank=True, max_length=20)),
                ('art_unit', models.CharField(blank=True, max_length=10)),
                ('summary', models.TextField(blank=True)),
                ('rejections', models.JSONField(default=list, help_text='Structured rejection data')),
                ('response_status', models.CharField(choices=[('pending', 'Response Pending'), ('in_progress', 'Response In Progress'), ('filed', 'Response Filed'), ('overdue', 'Response Overdue')], default='pending', max_length=20)),
                ('response_strategy', models.TextField(blank=True)),
                ('response_filed_date', models.DateField(blank=True, null=True)),
                ('office_action_document', models.CharField(blank=True, max_length=500)),
                ('response_document', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_actions', to='prosecution.patentapplication')),
            ],
            options={
                'db_table': 'office_actions',
                'ordering': ['-mailing_date'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_number', models.PositiveIntegerField()),
                ('claim_type', models.CharField(choices=[('independent', 'Independent Claim'), ('dependent', 'Dependent Claim'), ('multiple_dependent', 'Multiple Dependent Claim')], max_length=20)),
                ('claim_text', models.TextField()),
                ('is_cancelled', models.BooleanField(default=False)),
                ('is_amended', models.BooleanField(default=False)),
                ('rejection_history', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('depends_on', models.ManyToManyField(blank=True, related_name='dependents', to='prosecution.claim')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='prosecution.patentapplication')),
            ],
            options={
                'db_table': 'prosecution_claims',
                'ordering': ['claim_number'],
            },
        ),
        migrations.CreateModel(
            name='ProsecutionDeadline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deadline_type', models.CharField(choices=[('office_action_response', 'Office Action Response'), ('filing_deadline', 'Filing Deadline'), ('fee_payment', 'Fee Payment'), ('examination_request', 'Examination Request'), ('maintenance_fee', 'Maintenance Fee'), ('publication_request', 'Publication Request'), ('interview_deadline', 'Interview Deadline'), ('appeal_deadline', 'Appeal Deadline')], max_length=25)),
                ('due_date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_dates', models.JSONField(default=list, help_text='List of reminder dates')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='prosecution.patentapplication')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deadlines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prosecution_deadlines',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='ProsecutionDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('application', 'Patent Application'), ('specification', 'Specification'), ('claims', 'Claims'), ('drawings', 'Drawings'), ('office_action', 'Office Action'), ('response', 'Response to Office Action'), ('amendment', 'Amendment'), ('interview_summary', 'Interview Summary'), ('appeal', 'Appeal Brief'), ('petition', 'Petition'), ('correspondence', 'Correspondence'), ('fee_payment', 'Fee Payment Receipt'), ('power_of_attorney', 'Power of Attorney')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_type', models.CharField(max_length=10)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('is_current_version', models.BooleanField(default=True)),
                ('is_filed', models.BooleanField(default=False)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='prosecution.patentapplication')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prosecution_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProsecutionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('application_filed', 'Application Filed'), ('office_action_received', 'Office Action Received'), ('response_filed', 'Response Filed'), ('amendment_filed', 'Amendment Filed'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('allowance_received', 'Notice of Allowance'), ('patent_granted', 'Patent Granted'), ('abandonment', 'Application Abandoned'), ('continuation_filed', 'Continuation Filed'), ('appeal_filed', 'Appeal Filed'), ('fee_paid', 'Fee Payment'), ('deadline_reminder', 'Deadline Reminder')], max_length=30)),
                ('event_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('documents', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_urgent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='prosecution.patentapplication')),
                ('handled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prosecution_events',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='patentapplication',
            index=models.Index(fields=['organization', 'status'], name='patent_appl_organiz_a29a51_idx'),
        ),
        migrations.AddIndex(
            model_name='patentapplication',
            index=models.Index(fields=['attorney', 'status'], name='patent_appl_attorne_55ff44_idx'),
        ),
        migrations.AddIndex(
            model_name='patentapplication',
            index=models.Index(fields=['application_number'], name='patent_appl_applica_3c875e_idx'),
        ),
        migrations.AddIndex(
            model_name='patentapplication',
            index=models.Index(fields=['filing_date'], name='patent_appl_filing__ec4bc2_idx'),
        ),
        migrations.AddIndex(
            model_name='officeaction',
            index=models.Index(fields=['application', 'action_type'], name='office_acti_applica_8b5a6f_idx'),
        ),
        migrations.AddIndex(
            model_name='officeaction',
            index=models.Index(fields=['response_due_date', 'response_status'], name='office_acti_respons_052ddd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='claim',
            unique_together={('application', 'claim_number')},
        ),
        migrations.AddIndex(
            model_name='prosecutiondeadline',
            index=models.Index(fields=['due_date', 'is_completed'], name='prosecution_due_dat_04f14a_idx'),
        ),
        migrations.AddIndex(
            model_name='prosecutiondeadline',
            index=models.Index(fields=['assigned_to', 'is_completed'], name='prosecution_assigne_9707bc_idx'),
        ),
        migrations.AddIndex(
            model_name='prosecutiondeadline',
            index=models.Index(fields=['application', 'deadline_type'], name='prosecution_applica_3e59c4_idx'),
        ),
        migrations.AddIndex(
            model_name='prosecutiondocument',
            index=models.Index(fields=['application', 'document_type'], name='prosecution_applica_8bc8f7_idx'),
        ),
        migrations.AddIndex(
            model_name='prosecutiondocument',
            index=models.Index(fields=['is_current_version', 'document_type'], name='prosecution_is_curr_d018a0_idx'),
        ),
        migrations.AddIndex(
            model_name='prosecutionevent',
            index=models.Index(fields=['application', 'event_type'], name='prosecution_applica_28b1ac_idx'),
        ),
        migrations.AddIndex(
            model_name='prosecutionevent',
            index=models.Index(fields=['due_date', 'is_completed'], name='prosecution_due_dat_ab925a_idx'),
        ),
        migrations.AddIndex(
            model_name='prosecutionevent',
            index=models.Index(fields=['handled_by', 'is_completed'], name='prosecution_handled_b074c2_idx'),
        ),
    ]
