# Generated by Django 5.2.4 on 2026-02-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorney', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attorney',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attorney',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attorney',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attorney',
            name='govt_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attorney',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='attorney',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='attorney',
            name='practitioner_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='attorney',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('uspto_roster', 'USPTO Roster')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='attorney',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attorney',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attorney',
            name='suffix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('uspto_roster', 'USPTO Roster')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='attorney',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='attorney',
            name='experience_level',
            field=models.CharField(choices=[('junior', 'Junior (0-3 years)'), ('mid_level', 'Mid-Level (4-7 years)'), ('senior', 'Senior (8-15 years)'), ('partner', 'Partner (15+ years)'), ('unknown', 'Unknown')], default='mid_level', max_length=20),
        ),
        migrations.AlterField(
            model_name='attorney',
            name='registration_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='lawfirm',
            unique_together={('name', 'city', 'country')},
        ),
    ]
