# Generated by Django 5.2.4 on 2026-02-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorney', '0002_attorney_address_line_2_attorney_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attorney',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
