# Generated by Django 5.2.4 on 2026-02-15 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorney', '0003_alter_attorney_middle_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttorneySnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('registration_number', models.CharField(db_index=True, max_length=100)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(blank=True, max_length=50, null=True)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('firm_name', models.CharField(blank=True, max_length=255, null=True)),
                ('firm_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('practitioner_type', models.CharField(blank=True, max_length=30, null=True)),
                ('govt_employee', models.BooleanField(default=False)),
                ('attorney', models.ForeignKey(blank=True, db_column='attorney_registration_number', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='attorney.attorney', to_field='registration_number')),
            ],
            options={
                'verbose_name': 'Attorney Snapshot',
                'verbose_name_plural': 'Attorney Snapshots',
                'ordering': ['registration_number', 'snapshot_date'],
                'indexes': [models.Index(fields=['registration_number', 'snapshot_date'], name='attorney_at_registr_f271b8_idx'), models.Index(fields=['firm_name', 'snapshot_date'], name='attorney_at_firm_na_388e21_idx')],
                'unique_together': {('registration_number', 'snapshot_date')},
            },
        ),
    ]
