# Generated by Django 5.2.4 on 2026-02-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorney', '0004_attorneysnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawfirm',
            name='normalization_confidence',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('needs_review', 'Needs Review')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='normalized_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
