# Generated by Django 5.2.4 on 2026-02-21 08:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuotaUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('queries_used', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SearchSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('source_type', models.CharField(default='manual', max_length=50)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_text', models.CharField(max_length=2000)),
                ('category', models.CharField(choices=[('product_evidence', 'Product Evidence'), ('litigation', 'Litigation'), ('prior_art', 'Prior Art'), ('competitor', 'Competitor'), ('technical', 'Technical'), ('market', 'Market'), ('general', 'General')], default='general', max_length=30)),
                ('is_auto_generated', models.BooleanField(default=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('results_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='web_search.searchsession')),
            ],
            options={
                'ordering': ['category', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('url', models.URLField(max_length=2000)),
                ('snippet', models.TextField(blank=True)),
                ('display_link', models.CharField(blank=True, max_length=500)),
                ('source_domain', models.CharField(blank=True, max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('position', models.IntegerField(default=0)),
                ('is_flagged', models.BooleanField(default=False)),
                ('is_saved', models.BooleanField(default=False)),
                ('relevance_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='web_search.searchquery')),
            ],
            options={
                'ordering': ['position'],
                'indexes': [models.Index(fields=['is_flagged'], name='web_search__is_flag_0e7fc2_idx'), models.Index(fields=['is_saved'], name='web_search__is_save_3892bb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='searchsession',
            index=models.Index(fields=['source_type', 'source_id'], name='web_search__source__126791_idx'),
        ),
        migrations.AddIndex(
            model_name='searchsession',
            index=models.Index(fields=['-created_at'], name='web_search__created_f6eadc_idx'),
        ),
    ]
