# Generated by Django 5.2.4 on 2026-02-14 11:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchquery',
            name='api_source',
            field=models.CharField(choices=[('uspto', 'USPTO PatentsView API'), ('uspto_odp', 'USPTO Open Data Portal'), ('epo', 'European Patent Office API'), ('wipo', 'WIPO Global Brand Database'), ('lens', 'The Lens Patent Database'), ('google_patents', 'Google Patents Public Data')], max_length=50),
        ),
        migrations.CreateModel(
            name='PatentAPIConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Unique machine-readable name', max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('base_url', models.URLField(max_length=500)),
                ('auth_type', models.CharField(choices=[('none', 'No Authentication'), ('api_key', 'API Key'), ('bearer', 'Bearer Token'), ('basic', 'Basic Auth'), ('oauth2', 'OAuth 2.0')], default='none', max_length=20)),
                ('auth_config', models.JSONField(blank=True, default=dict, help_text='Signed credentials (API keys are stored signed)')),
                ('rate_limit', models.JSONField(blank=True, default=dict, help_text='{"requests_per_minute": 60, "requests_per_day": 10000}')),
                ('is_active', models.BooleanField(default=True)),
                ('query_mappings', models.JSONField(blank=True, default=dict)),
                ('response_mappings', models.JSONField(blank=True, default=dict)),
                ('query_templates', models.JSONField(blank=True, default=dict)),
                ('test_query', models.TextField(blank=True)),
                ('last_tested', models.DateTimeField(blank=True, null=True)),
                ('test_status', models.CharField(choices=[('never', 'Never Tested'), ('passed', 'Passed'), ('failed', 'Failed')], default='never', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_patent_api_configurations',
                'ordering': ['display_name'],
            },
        ),
    ]
