# Generated by Django 5.2.4 on 2026-02-14

from django.db import migrations


def seed_uspto_odp(apps, schema_editor):
    PatentAPIConfiguration = apps.get_model('analytics', 'PatentAPIConfiguration')
    PatentAPIConfiguration.objects.get_or_create(
        name='uspto_odp',
        defaults={
            'display_name': 'USPTO Open Data Portal',
            'description': 'USPTO ODP — US patent applications filed 2001+ with detailed prosecution, assignment, PTAB, and document data.',
            'base_url': 'https://api.uspto.gov/api/v1',
            'auth_type': 'api_key',
            'auth_config': {},
            'rate_limit': {'requests_per_minute': 60, 'requests_per_day': 10000},
            'is_active': True,
            'query_mappings': {
                'title': 'applicationMetaData.inventionTitle',
                'assignees': 'applicationMetaData.applicantBag',
                'application_date': 'applicationMetaData.filingDate',
                'ipc_classes': 'classificationDataBag.ipcClassificationDataBag.ipcClassificationText',
                'cpc_classes': 'classificationDataBag.cpcClassificationDataBag.cpcClassificationText',
            },
            'response_mappings': {
                'applicationMetaData.inventionTitle': 'title',
                'applicationNumberText': 'application_number',
                'applicationMetaData.filingDate': 'application_date',
                'applicationMetaData.applicantBag': 'assignee',
                'applicationMetaData.inventorBag': 'inventors',
            },
            'query_templates': {},
            'test_query': '{"q":"artificial intelligence","pagination":{"offset":0,"limit":1}}',
            'test_status': 'never',
        },
    )


def reverse_seed(apps, schema_editor):
    PatentAPIConfiguration = apps.get_model('analytics', 'PatentAPIConfiguration')
    PatentAPIConfiguration.objects.filter(name='uspto_odp').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_add_patent_api_configuration_and_odp_source'),
    ]

    operations = [
        migrations.RunPython(seed_uspto_odp, reverse_seed),
    ]
