# Generated by Django 5.2.4 on 2026-02-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_seed_uspto_odp_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='ODPCacheEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(db_index=True, max_length=64)),
                ('endpoint', models.CharField(max_length=50)),
                ('response_data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_odp_cache',
                'unique_together': {('application_id', 'endpoint')},
            },
        ),
    ]
