# Generated by Django 5.2.4 on 2026-02-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_odpcacheentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patentrecord',
            name='legal_status',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
