# Generated by Django 5.2.4 on 2026-02-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_alter_patentrecord_legal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patentrecord',
            name='country_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
