# Generated by Django 5.2.4 on 2026-02-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_alter_patentrecord_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patentdataset',
            name='data_source',
            field=models.CharField(choices=[('manual_upload', 'Manual Upload'), ('api_import', 'API Import'), ('database_query', 'Database Query'), ('web_scraping', 'Web Scraping'), ('portfolio_import', 'Portfolio Import'), ('odp_import', 'ODP API Import')], default='manual_upload', max_length=50),
        ),
    ]
