# Generated by Django 5.2.4 on 2026-03-06 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_prompt_templates'),
        ('patents', '0010_add_odp_raw_data'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='patentanalysisresult',
            new_name='analytics_p_applica_8ea3c6_idx',
            old_name='analytics_p_applica_idx',
        ),
        migrations.AddField(
            model_name='analyticsproject',
            name='portfolio',
            field=models.ForeignKey(blank=True, help_text='Portfolio being analysed — links this project to real patent data', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_projects', to='patents.portfolio'),
        ),
    ]
