# Generated by Django 5.2.4 on 2026-03-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_add_portfolio_fk_to_analytics_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnmappingrule',
            name='target_field',
            field=models.CharField(help_text='Field name in PatentRecord model', max_length=100, unique=True),
        ),
    ]
