# Generated by Django 5.2.4 on 2026-03-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_unique_column_mapping_rule_target_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='patentanalysisresult',
            name='analysis_type',
            field=models.CharField(blank=True, db_index=True, default='', help_text='e.g. landscape_analysis, family_analysis, investment_analysis', max_length=60),
        ),
        migrations.AddField(
            model_name='patentanalysisresult',
            name='extracted_entities',
            field=models.JSONField(blank=True, default=dict, help_text='Full algorithm/analysis result payload'),
        ),
        migrations.AddField(
            model_name='patentanalysisresult',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Contextual info: project name, who triggered, params'),
        ),
        migrations.AlterField(
            model_name='patentanalysisresult',
            name='model_used',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
