# Generated by Django 5.2.4 on 2026-03-28 18:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_add_analysis_type_and_extracted_entities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='researchquery',
            name='alert_thresholds',
            field=models.JSONField(blank=True, default=dict, help_text='Alert conditions: {"new_patents_min": 5, "new_assignee": true, "white_space_change": true}'),
        ),
        migrations.AddField(
            model_name='researchquery',
            name='is_watch',
            field=models.BooleanField(default=False, help_text='Whether this query is saved as a watch for periodic re-run'),
        ),
        migrations.AddField(
            model_name='researchquery',
            name='last_watch_run',
            field=models.DateTimeField(blank=True, help_text='When the watch was last run', null=True),
        ),
        migrations.AddField(
            model_name='researchquery',
            name='watch_cadence',
            field=models.CharField(blank=True, choices=[('', 'Not watched'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='', help_text='How often to re-run this watch query', max_length=20),
        ),
        migrations.AddField(
            model_name='researchquery',
            name='watch_diff',
            field=models.JSONField(blank=True, default=dict, help_text='Diff from last watch run'),
        ),
        migrations.AddIndex(
            model_name='researchquery',
            index=models.Index(fields=['is_watch', 'watch_cadence'], name='analytics_r_is_watc_176bb3_idx'),
        ),
    ]
