# Generated by Django 5.2.4 on 2026-04-04 22:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0014_add_watch_fields_to_research_query'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('patents', '0014_add_lens_id_to_patent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='analyticsproject',
            index=models.Index(fields=['status'], name='analytics_p_status_01d7f3_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsproject',
            index=models.Index(fields=['created_by'], name='analytics_p_created_10627d_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsproject',
            index=models.Index(fields=['priority'], name='analytics_p_priorit_d01c30_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsproject',
            index=models.Index(fields=['status', 'created_by'], name='analytics_p_status_bfacf9_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsproject',
            index=models.Index(fields=['-created_at'], name='analytics_p_created_cc7c92_idx'),
        ),
        migrations.AddIndex(
            model_name='patentdataset',
            index=models.Index(fields=['processing_status'], name='analytics_p_process_f50e01_idx'),
        ),
        migrations.AddIndex(
            model_name='patentdataset',
            index=models.Index(fields=['project', 'processing_status'], name='analytics_p_project_7c7774_idx'),
        ),
    ]
