# Generated by Django 5.2.4 on 2026-05-13 21:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0015_add_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundleType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('routing_rule_summary', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'analytics_bundle_type',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BundlingConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Default', max_length=200)),
                ('preset', models.CharField(choices=[('all_on', 'All ON'), ('npe', 'NPE / Counter-Assertion'), ('operating_company', 'Operating Company / FTO'), ('defensive', 'Defensive Aggregator'), ('standards', 'Standards Licensee'), ('ev_powertrain', 'EV Powertrain Sale')], default='all_on', max_length=50)),
                ('enabled_bundles', models.JSONField(default=dict)),
                ('thresholds', models.JSONField(default=dict)),
                ('gate_toggles', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundling_configurations', to='analytics.analyticsproject')),
            ],
            options={
                'db_table': 'analytics_bundling_configuration',
            },
        ),
        migrations.CreateModel(
            name='PatentBundleAttributes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('a1_primary_domain', models.CharField(blank=True, max_length=200)),
                ('a2_tech_subcategory', models.CharField(blank=True, max_length=200)),
                ('a3_stack_layer', models.CharField(blank=True, choices=[('App', 'App'), ('Middleware', 'Middleware'), ('Cloud', 'Cloud'), ('Hardware', 'Hardware'), ('OS', 'OS'), ('Protocol', 'Protocol')], max_length=50)),
                ('a4_subsystem', models.CharField(blank=True, max_length=200)),
                ('a5_use_case', models.CharField(blank=True, max_length=200)),
                ('b1_sep_potential', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('b2_standard_tagged', models.CharField(blank=True, max_length=200)),
                ('b3_interface_role', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('c1_claim_type', models.CharField(blank=True, choices=[('Method', 'Method'), ('Apparatus', 'Apparatus'), ('CRM', 'CRM'), ('System', 'System'), ('Composition', 'Composition')], max_length=50)),
                ('c2_breadth', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('c3_claim_count', models.IntegerField(blank=True, null=True)),
                ('c4_design_around_difficulty', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('d1_external_detectability', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('d2_teardown_detectability', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('d3_reads_on_products', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('e1_family_size', models.IntegerField(default=1)),
                ('e2_prosecution_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Granted', 'Granted'), ('Abandoned', 'Abandoned'), ('Expired', 'Expired')], max_length=50)),
                ('e3_continuation', models.BooleanField(blank=True, null=True)),
                ('e4_remaining_term_years', models.FloatField(blank=True, null=True)),
                ('e5_maintenance_status', models.CharField(blank=True, choices=[('Current', 'Current'), ('Lapsed', 'Lapsed'), ('Unknown', 'Unknown')], max_length=50)),
                ('f1_jurisdictions', models.JSONField(default=list)),
                ('f2_trilateral', models.BooleanField(blank=True, null=True)),
                ('f3_major_market_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('g1_convergence_theme', models.CharField(blank=True, max_length=200)),
                ('g2_generation_tag', models.CharField(blank=True, max_length=100)),
                ('g3_cross_industry_applicability', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('h1_claim_strength', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('h2_prior_art_exposure', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('h3_prosecution_risk', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('h4_divided_infringement_risk', models.BooleanField(blank=True, null=True)),
                ('h5_forward_citations', models.IntegerField(blank=True, null=True)),
                ('h6_backward_citations', models.IntegerField(blank=True, null=True)),
                ('h7_litigation_history', models.CharField(blank=True, choices=[('None', 'None'), ('Filed', 'Filed'), ('Survived', 'Survived'), ('Lost', 'Lost')], max_length=50)),
                ('h8_chain_of_title', models.CharField(blank=True, choices=[('Clean', 'Clean'), ('Issues', 'Issues'), ('Unknown', 'Unknown')], max_length=50)),
                ('h9_eou_availability', models.CharField(blank=True, choices=[('None', 'None'), ('Partial', 'Partial'), ('Full', 'Full')], max_length=50)),
                ('h10_encumbrance_status', models.CharField(blank=True, choices=[('None', 'None'), ('FRAND', 'FRAND'), ('Exclusive License', 'Exclusive License'), ('Other', 'Other')], max_length=50)),
                ('i1_product_mapping_confidence', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('i2_implementation_maturity', models.CharField(blank=True, choices=[('Concept', 'Concept'), ('Prototype', 'Prototype'), ('Commercial', 'Commercial'), ('Ubiquitous', 'Ubiquitous')], max_length=50)),
                ('i3_adjacent_market_reread', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('i4_workaround_complexity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('derived_fields', models.JSONField(default=list)),
                ('ai_extracted_fields', models.JSONField(default=list)),
                ('manually_set_fields', models.JSONField(default=list)),
                ('last_ai_extraction', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patent_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_attributes', to='analytics.patentrecord')),
            ],
            options={
                'db_table': 'analytics_patent_bundle_attributes',
            },
        ),
        migrations.CreateModel(
            name='BundleQualityScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patent_count', models.IntegerField(default=0)),
                ('avg_claim_strength', models.FloatField(blank=True, null=True)),
                ('avg_breadth', models.FloatField(blank=True, null=True)),
                ('pct_trilateral', models.FloatField(blank=True, null=True)),
                ('avg_remaining_term', models.FloatField(blank=True, null=True)),
                ('avg_detectability', models.FloatField(blank=True, null=True)),
                ('avg_forward_citations', models.FloatField(blank=True, null=True)),
                ('pct_sep', models.FloatField(blank=True, null=True)),
                ('pct_continuation_live', models.FloatField(blank=True, null=True)),
                ('gate_weakest_h1', models.IntegerField(blank=True, null=True)),
                ('gate_invalidity_exposure_pct', models.FloatField(blank=True, null=True)),
                ('gate_eou_ready_pct', models.FloatField(blank=True, null=True)),
                ('gate_survived_pct', models.FloatField(blank=True, null=True)),
                ('gate_cont_optionality_pct', models.FloatField(blank=True, null=True)),
                ('composition_hint', models.TextField(blank=True)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_quality_scores', to='analytics.analyticsproject')),
                ('bundle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_scores', to='analytics.bundletype')),
            ],
            options={
                'db_table': 'analytics_bundle_quality_score',
                'unique_together': {('project', 'bundle_type')},
            },
        ),
        migrations.CreateModel(
            name='BundleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_assigned', models.BooleanField(default=False)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_assignments', to='analytics.analyticsproject')),
                ('bundle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='analytics.bundletype')),
                ('patent_attributes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_assignments', to='analytics.patentbundleattributes')),
            ],
            options={
                'db_table': 'analytics_bundle_assignment',
                'indexes': [models.Index(fields=['project', 'bundle_type'], name='analytics_b_project_bbd9bb_idx'), models.Index(fields=['project', 'is_assigned'], name='analytics_b_project_9678b6_idx')],
                'unique_together': {('patent_attributes', 'bundle_type', 'project')},
            },
        ),
    ]
