# Generated by Django 5.2.4 on 2026-05-13 21:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0017_seed_bundle_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundlequalityscore',
            name='pioneer_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bundlequalityscore',
            name='strength_flag',
            field=models.CharField(blank=True, choices=[('STRONG', 'STRONG'), ('MODERATE', 'MODERATE'), ('WEAK', 'WEAK')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patentbundleattributes',
            name='h4_divided_infringement_risk',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='patentbundleattributes',
            name='i2_implementation_maturity',
            field=models.CharField(blank=True, choices=[('Concept', 'Concept'), ('Prototype', 'Prototype'), ('Productized', 'Productized'), ('Commercial', 'Commercial'), ('Ubiquitous', 'Ubiquitous')], max_length=50),
        ),
    ]
