# Generated by Django 5.2.4 on 2026-05-23 10:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0019_analytics_project_analysis_results'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('bundle_codes', models.JSONField(default=list, help_text='List of bundle codes included in this package')),
                ('transaction_type', models.CharField(choices=[('sale', 'Outright Sale'), ('license', 'License'), ('co_dev', 'Co-development'), ('cross', 'Cross-license')], default='sale', max_length=20)),
                ('asking_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('royalty_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('buyer_targets', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('sent', 'Sent'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_packages', to='analytics.analyticsproject')),
            ],
            options={
                'db_table': 'analytics_sales_package',
                'ordering': ['-created_at'],
            },
        ),
    ]
