# Generated by Django 5.2.4 on 2026-05-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0020_add_sales_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='salespackage',
            name='generated_listing',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salespackage',
            name='generated_teaser',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salespackage',
            name='listing_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salespackage',
            name='listing_pattern',
            field=models.CharField(blank=True, choices=[('A', 'Strategic Flagship'), ('B', 'Compressed Strategic'), ('C', 'Technical-Spec'), ('D', 'Single-Asset Narrow')], max_length=1),
        ),
        migrations.AddField(
            model_name='salespackage',
            name='listing_tier_report',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salespackage',
            name='mcl_entries',
            field=models.JSONField(default=list, help_text='Market Context Library — sourced T4 facts per package'),
        ),
        migrations.AddField(
            model_name='salespackage',
            name='primary_archetype',
            field=models.CharField(blank=True, choices=[('OC-DEF', 'Operating Co. — Defensive'), ('OC-OFF', 'Operating Co. — Offensive'), ('OC-EXP', 'Operating Co. — Market Expansion'), ('NPE-LIC', 'NPE — Licensing'), ('NPE-LIT', 'NPE — Litigation'), ('DEF-AGG', 'Defensive Aggregator'), ('LIT-FIN', 'Litigation Finance')], max_length=10),
        ),
        migrations.AddField(
            model_name='salespackage',
            name='secondary_archetype',
            field=models.CharField(blank=True, choices=[('OC-DEF', 'Operating Co. — Defensive'), ('OC-OFF', 'Operating Co. — Offensive'), ('OC-EXP', 'Operating Co. — Market Expansion'), ('NPE-LIC', 'NPE — Licensing'), ('NPE-LIT', 'NPE — Litigation'), ('DEF-AGG', 'Defensive Aggregator'), ('LIT-FIN', 'Litigation Finance')], max_length=10),
        ),
    ]
