# Generated by Django 5.2.4 on 2026-05-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0024_ai_confidence_scores_and_prompts'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmproviderconfig',
            name='model_name',
            field=models.CharField(blank=True, default='', help_text='Leave blank to use the provider default. See MODELS_BY_PROVIDER for valid values.', max_length=100),
        ),
        migrations.AlterField(
            model_name='analysisprompttemplate',
            name='section',
            field=models.CharField(choices=[('keywords', 'Keyword Extraction'), ('novel_elements', 'Novel Element Identification'), ('claim_scope', 'Claim Scope & Broadness'), ('embodiments', 'Embodiment Analysis'), ('background_analysis', 'Background & Problem Analysis'), ('means_plus_function', 'Means-Plus-Function Detection'), ('vulnerabilities', 'Prosecution Vulnerability Assessment'), ('bundle_attribute_extraction', 'Bundle Attribute Extraction (Groups H & I)'), ('group_a_classification', 'Technology Classification (Group A)'), ('group_b_standards', 'Standards & Ecosystem (B1-B3)'), ('group_c_claim_analysis', 'Claim Analysis (C1-C2-C4)'), ('group_d_detectability', 'Detectability (D1-D2)'), ('group_g_themes', 'Themes & Generation (G1-G2-G3)'), ('group_h_quality', 'Claim Quality (H1-H4)'), ('group_i_market', 'Market Signals (I2-I3-I4)')], max_length=30),
        ),
    ]
