# Generated by Django 5.2.4 on 2026-05-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0025_add_model_name_to_llm_provider_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='patentbundleattributes',
            name='a21_tech_detail',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='patentbundleattributes',
            name='a22_tech_niche',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
