# Generated by Django 5.2.4 on 2026-05-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0026_add_a21_a22_tech_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='patentrecord',
            name='description',
            field=models.TextField(blank=True, help_text='Full patent specification / detailed description text'),
        ),
    ]
