# Generated by Django 5.2.4 on 2025-09-13 17:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_add_data_configuration_permissions'),
        ('projects', '0004_importbatch_importedpatent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Portfolio name', max_length=200)),
                ('company_name', models.CharField(help_text='Company/Client name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Portfolio description')),
                ('total_patents', models.IntegerField(default=0)),
                ('active_patents', models.IntegerField(default=0)),
                ('pending_patents', models.IntegerField(default=0)),
                ('expired_patents', models.IntegerField(default=0)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('annual_maintenance_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patent_portfolios', to='accounts.organization')),
                ('owner', models.ForeignKey(help_text='Portfolio owner or manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patent_portfolios',
                'ordering': ['company_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_level', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('manager', 'Manager'), ('owner', 'Owner')], default='viewer', max_length=20)),
                ('can_view', models.BooleanField(default=True)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_access_grants', to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patents.portfolio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portfolio_access',
            },
        ),
        migrations.AddField(
            model_name='portfolio',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='accessible_portfolios', through='patents.PortfolioAccess', through_fields=('portfolio', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('application_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('patent_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('filed', 'Filed'), ('pending', 'Pending'), ('granted', 'Granted'), ('expired', 'Expired'), ('abandoned', 'Abandoned')], default='draft', max_length=20)),
                ('patent_type', models.CharField(choices=[('utility', 'Utility Patent'), ('design', 'Design Patent'), ('plant', 'Plant Patent'), ('provisional', 'Provisional Patent')], default='utility', max_length=20)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('priority_date', models.DateField(blank=True, null=True)),
                ('grant_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('inventors', models.JSONField(blank=True, default=list)),
                ('assignees', models.JSONField(blank=True, default=list)),
                ('technology_area', models.CharField(blank=True, max_length=200)),
                ('ipc_classifications', models.JSONField(blank=True, default=list)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('maintenance_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('abstract', models.TextField(blank=True)),
                ('claims', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patents', to='projects.project')),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patents', to='patents.portfolio')),
            ],
            options={
                'db_table': 'patents',
                'ordering': ['-filing_date', 'title'],
                'indexes': [models.Index(fields=['portfolio'], name='patents_portfol_e74f52_idx'), models.Index(fields=['status'], name='patents_status_b3314d_idx'), models.Index(fields=['patent_type'], name='patents_patent__b34dcd_idx'), models.Index(fields=['filing_date'], name='patents_filing__9e0379_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='portfolioaccess',
            index=models.Index(fields=['portfolio', 'user'], name='portfolio_a_portfol_538750_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioaccess',
            index=models.Index(fields=['user'], name='portfolio_a_user_id_b9ff84_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioaccess',
            unique_together={('portfolio', 'user')},
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['organization'], name='patent_port_organiz_49a031_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['owner'], name='patent_port_owner_i_f59dcf_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['is_active'], name='patent_port_is_acti_83348a_idx'),
        ),
    ]
