# Generated by Django 5.2.4 on 2026-02-14 18:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ODPImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('search_params', models.JSONField(default=dict)),
                ('selected_patents_data', models.JSONField(default=list)),
                ('total_expected', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processed', models.IntegerField(default=0)),
                ('created_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odp_import_jobs', to='patents.portfolio')),
            ],
            options={
                'db_table': 'odp_import_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['portfolio', 'status'], name='odp_import__portfol_1e6869_idx')],
            },
        ),
    ]
