# Generated by Django 5.2.4 on 2026-02-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0003_alter_odpimportjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='odpimportjob',
            name='page_size',
            field=models.IntegerField(default=25),
        ),
    ]
