# Generated by Django 5.2.4 on 2026-02-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0004_odpimportjob_page_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='odpimportjob',
            name='import_fields',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
