# Generated by Django 5.2.4 on 2026-02-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0005_odpimportjob_import_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odpimportjob',
            name='page_size',
            field=models.IntegerField(default=100),
        ),
    ]
