# Generated by Django 5.2.4 on 2026-02-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0006_change_default_page_size_to_100'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='estimated_odp_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
