# Generated by Django 5.2.4 on 2026-02-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0007_add_estimated_odp_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('system', models.CharField(choices=[('IPC', 'IPC'), ('CPC', 'CPC')], max_length=3)),
                ('level', models.CharField(choices=[('section', 'Section'), ('class', 'Class'), ('subclass', 'Subclass'), ('group', 'Main Group'), ('subgroup', 'Subgroup')], max_length=10)),
                ('title', models.TextField()),
                ('parent_code', models.CharField(blank=True, db_index=True, max_length=30)),
            ],
            options={
                'db_table': 'classification_definitions',
                'indexes': [models.Index(fields=['system', 'level'], name='classificat_system_215b4b_idx'), models.Index(fields=['code'], name='classificat_code_cdbce4_idx')],
                'unique_together': {('code', 'system')},
            },
        ),
    ]
