# Generated by Django 5.2.4 on 2026-02-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0008_add_classification_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationdefinition',
            name='indent_level',
            field=models.SmallIntegerField(default=0),
        ),
    ]
