# Generated by Django 5.2.4 on 2026-02-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0009_add_indent_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='odp_raw_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
