# Generated by Django 5.2.4 on 2026-03-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0011_odpenrichmentjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='odpenrichmentjob',
            name='filters',
            field=models.JSONField(blank=True, default=dict, help_text='Query filters: {status: [...], patent_type: [...]}'),
        ),
    ]
