# Generated by Django 5.2.4 on 2026-03-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0013_add_data_source_to_enrichment_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='lens_id',
            field=models.CharField(blank=True, db_index=True, help_text='Lens.org unique identifier', max_length=50),
        ),
    ]
