# Generated by Django 5.2.4 on 2026-05-28 20:54
#
# Adds cpc_classifications and uspc_classifications fields to Patent.
# Restores the odp_raw_data field declaration on the model (the DB column
# already exists from migration 0010_add_odp_raw_data); this migration is
# a no-op for the DB but realigns Django's model state.
#
# The auto-detector also wanted to drop lens_id and delete ODPEnrichmentJob,
# but those still have live data in production. We use SeparateDatabaseAndState
# to bring the model state into alignment WITHOUT touching the DB.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0014_add_lens_id_to_patent'),
    ]

    operations = [
        # Real schema changes — add two new typed classification fields.
        migrations.AddField(
            model_name='patent',
            name='cpc_classifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='patent',
            name='uspc_classifications',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
