# Generated by Django 5.2.4 on 2026-05-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0015_add_cpc_uspc_classifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patent',
            name='description_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patent',
            name='description_source',
            field=models.CharField(blank=True, default='', help_text="'grant', 'pgpub', or '' if not loaded", max_length=20),
        ),
        # ODPEnrichmentJob removal intentionally omitted — the table still has live data
        # in production. See migration 0015 for the same pattern.
    ]
