# Generated by Django 5.2.4 on 2025-08-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(help_text='Project type ID - references ProjectType model', max_length=100),
        ),
    ]
