# Generated by Django 5.2.4 on 2025-08-06 08:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurableProjectType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('required_fields', models.JSONField(default=list, help_text='List of required fields for this project type')),
                ('estimated_duration', models.IntegerField(blank=True, help_text='Estimated duration in days', null=True)),
                ('color', models.CharField(blank=True, help_text='Hex color code', max_length=7, null=True)),
                ('permissions', models.JSONField(default=list, help_text='Required permissions for this project type')),
                ('min_role_level', models.CharField(choices=[('viewer', 'Viewer'), ('paralegal', 'Paralegal'), ('attorney', 'Attorney'), ('lead_attorney', 'Lead Attorney'), ('admin', 'Admin')], default='viewer', max_length=20)),
                ('display_order', models.IntegerField(default=0, help_text='Order for displaying in UI')),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configurable Project Type',
                'verbose_name_plural': 'Configurable Project Types',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
