# Generated by Django 5.2.4 on 2025-08-16 18:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_configurableprojecttype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_name', models.CharField(blank=True, max_length=200)),
                ('batch_description', models.TextField(blank=True)),
                ('source_filename', models.CharField(max_length=255)),
                ('total_rows', models.IntegerField(default=0)),
                ('successful_imports', models.IntegerField(default=0)),
                ('failed_imports', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partially Completed')], default='processing', max_length=20)),
                ('import_settings', models.JSONField(default=dict, help_text='Column mappings and import configuration')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_log', models.JSONField(default=list, help_text='List of errors encountered during import')),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patent_import_batches', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='projects.project')),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportedPatent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patent_id', models.CharField(db_index=True, max_length=100)),
                ('title', models.TextField()),
                ('abstract', models.TextField(blank=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('application_date', models.DateField(blank=True, null=True)),
                ('priority_date', models.DateField(blank=True, null=True)),
                ('publication_number', models.CharField(blank=True, max_length=100)),
                ('application_number', models.CharField(blank=True, max_length=100)),
                ('family_id', models.CharField(blank=True, max_length=100)),
                ('assignee', models.TextField(blank=True)),
                ('inventors', models.JSONField(default=list, help_text='List of inventor names')),
                ('ipc_classes', models.JSONField(default=list, help_text='IPC classification codes')),
                ('cpc_classes', models.JSONField(default=list, help_text='CPC classification codes')),
                ('jurisdiction', models.CharField(blank=True, max_length=10)),
                ('legal_status', models.CharField(blank=True, max_length=100)),
                ('keywords', models.TextField(blank=True)),
                ('citations', models.JSONField(default=list, help_text='List of cited patents')),
                ('is_selected', models.BooleanField(default=False)),
                ('manual_relevance', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('not_relevant', 'Not Relevant')], max_length=20)),
                ('relevance_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('user_notes', models.TextField(blank=True)),
                ('source_row_number', models.IntegerField(blank=True, help_text='Row number in source file', null=True)),
                ('import_errors', models.JSONField(default=list, help_text='Validation errors during import')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_imported_patents', to=settings.AUTH_USER_MODEL)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patents', to='projects.importbatch')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_patents', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['project', 'status'], name='projects_im_project_937afe_idx'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['imported_by', 'imported_at'], name='projects_im_importe_5712a1_idx'),
        ),
        migrations.AddIndex(
            model_name='importedpatent',
            index=models.Index(fields=['project', 'is_deleted'], name='projects_im_project_576751_idx'),
        ),
        migrations.AddIndex(
            model_name='importedpatent',
            index=models.Index(fields=['import_batch', 'is_deleted'], name='projects_im_import__b5d69d_idx'),
        ),
        migrations.AddIndex(
            model_name='importedpatent',
            index=models.Index(fields=['patent_id', 'project'], name='projects_im_patent__31dd17_idx'),
        ),
        migrations.AddIndex(
            model_name='importedpatent',
            index=models.Index(fields=['is_selected', 'project'], name='projects_im_is_sele_68bc58_idx'),
        ),
        migrations.AddIndex(
            model_name='importedpatent',
            index=models.Index(fields=['manual_relevance', 'project'], name='projects_im_manual__5141ca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='importedpatent',
            unique_together={('project', 'patent_id', 'is_deleted')},
        ),
    ]
