# Generated by Django 5.2.4 on 2026-02-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_importbatch_importedpatent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedpatent',
            name='jurisdiction',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
