# Generated by Django 5.2.4 on 2026-04-05 08:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FCCQueryJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('query_type', models.CharField(choices=[('fcc_id', 'FCC ID Search'), ('whitespace', 'Whitespace Authorizations'), ('cbsd', 'CBSD Authorizations'), ('afc', 'AFC Authorizations')], max_length=30)),
                ('fcc_id', models.CharField(blank=True, default='', max_length=50)),
                ('begin_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('task_id', models.CharField(blank=True, default='', max_length=255)),
                ('results_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('raw_response', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fcc_query_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FCCExportFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='fcc_exports/%Y/%m/')),
                ('filename', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON'), ('pdf', 'PDF')], max_length=10)),
                ('record_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='fcc_data.fccqueryjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FCCAuthorization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fcc_id', models.CharField(max_length=50)),
                ('grantee_name', models.CharField(blank=True, default='', max_length=500)),
                ('application_purpose', models.CharField(blank=True, default='', max_length=200)),
                ('equipment_class', models.CharField(blank=True, default='', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('grant_date', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(blank=True, default='', max_length=10)),
                ('status_date', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('city', models.CharField(blank=True, default='', max_length=200)),
                ('state', models.CharField(blank=True, default='', max_length=50)),
                ('zip_code', models.CharField(blank=True, default='', max_length=20)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('freq_min', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('freq_max', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('power_output', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('emission_designator', models.CharField(blank=True, default='', max_length=50)),
                ('grant_notes', models.JSONField(blank=True, default=list)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='fcc_data.fccqueryjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='fccqueryjob',
            index=models.Index(fields=['-created_at'], name='fcc_data_fc_created_016e76_idx'),
        ),
        migrations.AddIndex(
            model_name='fccqueryjob',
            index=models.Index(fields=['status'], name='fcc_data_fc_status_fc9c48_idx'),
        ),
        migrations.AddIndex(
            model_name='fccqueryjob',
            index=models.Index(fields=['query_type'], name='fcc_data_fc_query_t_0fcb3f_idx'),
        ),
        migrations.AddIndex(
            model_name='fccauthorization',
            index=models.Index(fields=['job', 'fcc_id'], name='fcc_data_fc_job_id_f5b712_idx'),
        ),
        migrations.AddIndex(
            model_name='fccauthorization',
            index=models.Index(fields=['fcc_id'], name='fcc_data_fc_fcc_id_68f3cc_idx'),
        ),
        migrations.AddIndex(
            model_name='fccauthorization',
            index=models.Index(fields=['grantee_name'], name='fcc_data_fc_grantee_499470_idx'),
        ),
        migrations.AddIndex(
            model_name='fccauthorization',
            index=models.Index(fields=['equipment_class'], name='fcc_data_fc_equipme_deea2a_idx'),
        ),
        migrations.AddIndex(
            model_name='fccauthorization',
            index=models.Index(fields=['job', '-created_at'], name='fcc_data_fc_job_id_5a50c0_idx'),
        ),
    ]
