# Generated by Django 5.2.4 on 2026-04-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcc_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fccqueryjob',
            name='product_code',
            field=models.CharField(blank=True, default='', help_text='Optional product code (appended to grantee code)', max_length=50),
        ),
        migrations.AlterField(
            model_name='fccqueryjob',
            name='fcc_id',
            field=models.CharField(blank=True, default='', help_text='Grantee code (3-5 chars) or full FCC ID', max_length=50),
        ),
    ]
