# Generated by Django 5.2.4 on 2026-04-05 16:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcc_data', '0002_fccqueryjob_product_code_alter_fccqueryjob_fcc_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCCDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fcc_id', models.CharField(max_length=50)),
                ('exhibit_name', models.CharField(max_length=500)),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
                ('document_url', models.URLField(max_length=2000)),
                ('document_type', models.CharField(choices=[('test_report', 'Test Report'), ('external_photos', 'External Photos'), ('internal_photos', 'Internal Photos'), ('schematics', 'Schematics'), ('block_diagram', 'Block Diagram'), ('user_manual', 'User Manual'), ('label', 'Label'), ('sar_report', 'SAR Report'), ('attestation', 'Attestation'), ('cover_letter', 'Cover Letter'), ('other', 'Other')], default='other', max_length=50)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('is_downloaded', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, default='', upload_to='fcc_documents/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, default='', max_length=500)),
                ('mime_type', models.CharField(blank=True, default='', max_length=200)),
                ('download_error', models.TextField(blank=True, default='')),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fcc_data.fccqueryjob')),
            ],
            options={
                'ordering': ['document_type', 'exhibit_name'],
                'indexes': [models.Index(fields=['job', 'fcc_id'], name='fcc_data_fc_job_id_6d7ef2_idx'), models.Index(fields=['fcc_id'], name='fcc_data_fc_fcc_id_2061c7_idx'), models.Index(fields=['document_type'], name='fcc_data_fc_documen_bc2a20_idx')],
            },
        ),
    ]
