# Generated by Django 5.2.4 on 2026-04-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcc_data', '0003_fccdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='fccqueryjob',
            name='bulk_fcc_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of FCC IDs for bulk search'),
        ),
        migrations.AlterField(
            model_name='fccqueryjob',
            name='query_type',
            field=models.CharField(choices=[('fcc_id', 'FCC ID Search'), ('bulk_fcc_id', 'Bulk FCC ID Search'), ('whitespace', 'Whitespace Authorizations'), ('cbsd', 'CBSD Authorizations'), ('afc', 'AFC Authorizations')], max_length=30),
        ),
    ]
