# Generated by Django 5.2.4 on 2026-04-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcc_data', '0004_fccqueryjob_bulk_fcc_ids_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCCGrantee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grantee_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('grantee_name', models.CharField(max_length=500)),
                ('mailing_address', models.CharField(blank=True, default='', max_length=1000)),
                ('po_box', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=200)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('zip_code', models.CharField(blank=True, default='', max_length=20)),
                ('contact_name', models.CharField(blank=True, default='', max_length=300)),
                ('date_received', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'ordering': ['grantee_name'],
                'indexes': [models.Index(fields=['grantee_name'], name='fcc_data_fc_grantee_9fea97_idx'), models.Index(fields=['country'], name='fcc_data_fc_country_a74d85_idx')],
            },
        ),
    ]
