# Generated by Django 5.2.4 on 2026-04-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcc_data', '0005_fccgrantee'),
    ]

    operations = [
        migrations.AddField(
            model_name='fccqueryjob',
            name='grantee_search_term',
            field=models.CharField(blank=True, default='', help_text='Company name search term for grantee search', max_length=500),
        ),
        migrations.AlterField(
            model_name='fccqueryjob',
            name='query_type',
            field=models.CharField(choices=[('fcc_id', 'FCC ID Search'), ('bulk_fcc_id', 'Bulk FCC ID Search'), ('grantee_search', 'Grantee Name Search'), ('whitespace', 'Whitespace Authorizations'), ('cbsd', 'CBSD Authorizations'), ('afc', 'AFC Authorizations')], max_length=30),
        ),
    ]
