# Generated by Django 5.2.4 on 2026-04-05 07:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('target_url', models.URLField(max_length=2000)),
                ('max_depth', models.PositiveIntegerField(default=2)),
                ('max_pages', models.PositiveIntegerField(default=100)),
                ('allowed_domains', models.JSONField(blank=True, default=list)),
                ('url_patterns_include', models.JSONField(blank=True, default=list)),
                ('url_patterns_exclude', models.JSONField(blank=True, default=list)),
                ('crawl_delay', models.FloatField(default=2.0, help_text='Seconds between requests (1-5)')),
                ('proxy_url', models.URLField(blank=True, default='', max_length=2000)),
                ('save_rendered_pages', models.BooleanField(default=True, help_text='Auto-save rendered HTML/PDF when no downloadable doc found for product pages')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('crawling', 'Crawling'), ('paused', 'Paused'), ('discovered', 'Discovered'), ('downloading', 'Downloading'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('crawl_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('download_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('progress', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('crawl_queue', models.JSONField(blank=True, default=list)),
                ('visited_urls', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawl_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscoveredLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2000)),
                ('title', models.CharField(blank=True, default='', max_length=1000)),
                ('link_text', models.CharField(blank=True, default='', max_length=1000)),
                ('parent_url', models.URLField(blank=True, default='', max_length=2000)),
                ('depth', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('product_page', 'Product Page'), ('technical_doc', 'Technical Documentation'), ('datasheet', 'Datasheet'), ('legal_ip', 'Legal / IP'), ('marketing', 'Marketing'), ('image', 'Image'), ('pdf', 'PDF'), ('document', 'Document'), ('page', 'Web Page'), ('other', 'Other')], default='page', max_length=50)),
                ('content_type', models.CharField(blank=True, default='', max_length=200)),
                ('file_extension', models.CharField(blank=True, default='', max_length=20)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('is_downloaded', models.BooleanField(default=False)),
                ('download_error', models.TextField(blank=True, default='')),
                ('meta_description', models.TextField(blank=True, default='')),
                ('meta_keywords', models.TextField(blank=True, default='')),
                ('has_downloadable_doc', models.BooleanField(default=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='doc_download.crawljob')),
            ],
            options={
                'ordering': ['-discovered_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='doc_downloads/%Y/%m/')),
                ('original_filename', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, default='', max_length=200)),
                ('category', models.CharField(choices=[('product_page', 'Product Page'), ('technical_doc', 'Technical Documentation'), ('datasheet', 'Datasheet'), ('legal_ip', 'Legal / IP'), ('marketing', 'Marketing'), ('image', 'Image'), ('pdf', 'PDF'), ('document', 'Document'), ('page', 'Web Page'), ('other', 'Other')], default='other', max_length=50)),
                ('is_rendered_page', models.BooleanField(default=False, help_text='True if this is a saved rendered HTML/PDF (no original downloadable doc found)')),
                ('checksum_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('access_count', models.IntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloaded_files', to='doc_download.crawljob')),
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='downloaded_file', to='doc_download.discoveredlink')),
            ],
            options={
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='crawljob',
            index=models.Index(fields=['-created_at'], name='doc_downloa_created_1d42ae_idx'),
        ),
        migrations.AddIndex(
            model_name='crawljob',
            index=models.Index(fields=['status'], name='doc_downloa_status_605f39_idx'),
        ),
        migrations.AddIndex(
            model_name='crawljob',
            index=models.Index(fields=['created_by', '-created_at'], name='doc_downloa_created_95bdf3_idx'),
        ),
        migrations.AddIndex(
            model_name='discoveredlink',
            index=models.Index(fields=['job', 'category'], name='doc_downloa_job_id_46a5f6_idx'),
        ),
        migrations.AddIndex(
            model_name='discoveredlink',
            index=models.Index(fields=['job', 'is_selected'], name='doc_downloa_job_id_332551_idx'),
        ),
        migrations.AddIndex(
            model_name='discoveredlink',
            index=models.Index(fields=['job', 'is_downloaded'], name='doc_downloa_job_id_c59f4f_idx'),
        ),
        migrations.AddIndex(
            model_name='discoveredlink',
            index=models.Index(fields=['url'], name='doc_downloa_url_eecf58_idx'),
        ),
        migrations.AddIndex(
            model_name='discoveredlink',
            index=models.Index(fields=['job', '-discovered_at'], name='doc_downloa_job_id_8600bf_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadedfile',
            index=models.Index(fields=['job', 'category'], name='doc_downloa_job_id_755ea0_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadedfile',
            index=models.Index(fields=['checksum_sha256'], name='doc_downloa_checksu_b9257f_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadedfile',
            index=models.Index(fields=['job', '-downloaded_at'], name='doc_downloa_job_id_062302_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadedfile',
            index=models.Index(fields=['job', 'is_rendered_page'], name='doc_downloa_job_id_f540f7_idx'),
        ),
    ]
