# Generated by Django 5.2.4 on 2025-08-06 11:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_userprofile_usersettings'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('object_id', models.UUIDField()),
                ('progress_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('current_step_order', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('actual_duration', models.IntegerField(blank=True, help_text='Actual duration in hours', null=True)),
                ('quality_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('configuration_overrides', models.JSONField(blank=True, default=dict, help_text='Instance-specific configuration overrides')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('audit_log', models.JSONField(blank=True, default=list, help_text='Audit trail of workflow execution')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workflow_instances', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_workflow_instances', to=settings.AUTH_USER_MODEL)),
                ('final_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_workflows', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_instances', to='accounts.organization')),
                ('participants', models.ManyToManyField(blank=True, related_name='workflow_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('step_type', models.CharField(choices=[('manual', 'Manual Task'), ('automated', 'Automated Check'), ('approval', 'Approval Required'), ('document', 'Document Upload'), ('review', 'Review & Feedback'), ('quality_gate', 'Quality Control Gate'), ('notification', 'Send Notification')], default='manual', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('is_parallel', models.BooleanField(default=False, help_text='Can execute in parallel with other steps')),
                ('auto_complete', models.BooleanField(default=False, help_text='Auto-complete when conditions met')),
                ('estimated_duration', models.IntegerField(blank=True, help_text='Estimated duration in hours', null=True)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('assigned_role', models.CharField(blank=True, help_text='Role required to execute this step', max_length=50)),
                ('quality_criteria', models.JSONField(blank=True, default=dict, help_text='Quality validation criteria for this step')),
                ('required_approvals', models.IntegerField(default=0, help_text='Number of approvals required')),
                ('approver_roles', models.JSONField(blank=True, default=list, help_text='Roles that can approve this step')),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Step-specific configuration options')),
                ('actions', models.JSONField(blank=True, default=list, help_text='Actions to be performed in this step')),
                ('validations', models.JSONField(blank=True, default=list, help_text='Validation rules for step completion')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_user', models.ForeignKey(blank=True, help_text='Specific user assignment (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workflow_steps', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_workflow_steps', to=settings.AUTH_USER_MODEL)),
                ('depends_on', models.ManyToManyField(blank=True, related_name='dependent_steps', to='workflows.workflowstep')),
            ],
            options={
                'ordering': ['workflow_template', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QualityControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('automated', 'Automated Check'), ('manual', 'Manual Review'), ('checklist', 'Checklist Validation'), ('peer_review', 'Peer Review'), ('expert_review', 'Expert Review'), ('compliance', 'Compliance Check')], max_length=20)),
                ('criteria', models.JSONField(default=dict, help_text='Quality criteria and validation rules')),
                ('passing_score', models.IntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('on_pass_actions', models.JSONField(blank=True, default=list, help_text='Actions to execute when quality check passes')),
                ('on_fail_actions', models.JSONField(blank=True, default=list, help_text='Actions to execute when quality check fails')),
                ('is_required', models.BooleanField(default=True)),
                ('is_blocking', models.BooleanField(default=True, help_text='Block workflow progression if quality check fails')),
                ('auto_remediate', models.BooleanField(default=False, help_text='Automatically attempt to fix issues')),
                ('reviewer_roles', models.JSONField(blank=True, default=list, help_text='Roles that can perform this quality review')),
                ('required_reviewers', models.IntegerField(default=1)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('weight', models.IntegerField(default=1, help_text='Weight of this quality control in overall scoring')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_quality_controls', to=settings.AUTH_USER_MODEL)),
                ('workflow_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_controls', to='workflows.workflowstep')),
            ],
            options={
                'ordering': ['workflow_template', 'workflow_step', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStepInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('waiting_approval', 'Waiting Approval'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('quality_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('output_data', models.JSONField(blank=True, default=dict, help_text='Step execution results and outputs')),
                ('notes', models.TextField(blank=True)),
                ('feedback', models.TextField(blank=True)),
                ('step_configuration', models.JSONField(blank=True, default=dict, help_text='Step-specific configuration for this instance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_step_instances', to=settings.AUTH_USER_MODEL)),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_instances', to='workflows.workflowinstance')),
                ('workflow_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_instances', to='workflows.workflowstep')),
            ],
            options={
                'ordering': ['workflow_instance', 'workflow_step__order'],
            },
        ),
        migrations.CreateModel(
            name='QualityCheckResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passed', models.BooleanField()),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('details', models.JSONField(default=dict, help_text='Detailed results and findings')),
                ('review_notes', models.TextField(blank=True)),
                ('requires_remediation', models.BooleanField(default=False)),
                ('remediation_actions', models.JSONField(blank=True, default=list)),
                ('remediated_at', models.DateTimeField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_reviews', to=settings.AUTH_USER_MODEL)),
                ('quality_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_results', to='workflows.qualitycontrol')),
                ('step_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_results', to='workflows.workflowstepinstance')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_template', models.BooleanField(default=True)),
                ('estimated_duration', models.IntegerField(blank=True, help_text='Estimated duration in days', null=True)),
                ('auto_assign', models.BooleanField(default=False, help_text='Auto-assign steps based on roles')),
                ('require_sequential', models.BooleanField(default=True, help_text='Steps must be completed in order')),
                ('allow_parallel', models.BooleanField(default=False, help_text='Allow parallel step execution')),
                ('quality_threshold', models.IntegerField(default=80, help_text='Minimum quality score required (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('require_approval', models.BooleanField(default=False, help_text='Require final approval')),
                ('permissions', models.JSONField(default=list, help_text='Required permissions for this workflow')),
                ('min_role_level', models.CharField(choices=[('viewer', 'Viewer'), ('paralegal', 'Paralegal'), ('attorney', 'Attorney'), ('lead_attorney', 'Lead Attorney'), ('admin', 'Admin')], default='viewer', max_length=20)),
                ('usage_count', models.IntegerField(default=0)),
                ('success_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Success rate percentage', max_digits=5)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('color', models.CharField(blank=True, help_text='Hex color code', max_length=7, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order for displaying in UI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_workflow_templates', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_templates', to='accounts.organization')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='workflow_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflows.workflowtemplate'),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='workflow_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='workflows.workflowtemplate'),
        ),
        migrations.AddField(
            model_name='qualitycontrol',
            name='workflow_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_controls', to='workflows.workflowtemplate'),
        ),
        migrations.AddIndex(
            model_name='workflowstepinstance',
            index=models.Index(fields=['workflow_instance', 'status'], name='workflows_w_workflo_d8fb76_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowstepinstance',
            index=models.Index(fields=['assigned_to', 'status'], name='workflows_w_assigne_7d883a_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowstepinstance',
            index=models.Index(fields=['due_date', 'status'], name='workflows_w_due_dat_69bac4_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowtemplate',
            index=models.Index(fields=['category', 'is_active'], name='workflows_w_categor_efb57e_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowtemplate',
            index=models.Index(fields=['organization', 'is_active'], name='workflows_w_organiz_af8959_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowtemplate',
            index=models.Index(fields=['created_by', 'created_at'], name='workflows_w_created_9f3a46_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowstep',
            index=models.Index(fields=['workflow_template', 'order'], name='workflows_w_workflo_b758db_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowstep',
            index=models.Index(fields=['assigned_user', 'step_type'], name='workflows_w_assigne_39b565_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['status', 'priority'], name='workflows_w_status_69cc71_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['content_type', 'object_id'], name='workflows_w_content_9e540a_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['assigned_to', 'status'], name='workflows_w_assigne_4622d5_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['organization', 'status'], name='workflows_w_organiz_67cdba_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['due_date', 'status'], name='workflows_w_due_dat_96d8a7_idx'),
        ),
    ]
