# Generated by Django 5.2.4 on 2025-08-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowinstance',
            name='template_version',
            field=models.CharField(blank=True, help_text='Version of template used when instance was created', max_length=20),
        ),
    ]
