# Generated by Django 5.2.4 on 2025-08-06 17:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_add_rbac_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workflowcollaborator',
            name='unique_workflow_collaborator',
        ),
        migrations.RemoveConstraint(
            model_name='workflowroleassignment',
            name='unique_user_role_instance',
        ),
        migrations.RemoveConstraint(
            model_name='workflowroleassignment',
            name='unique_user_role_template',
        ),
        migrations.RemoveConstraint(
            model_name='workflowtemplateversion',
            name='unique_template_version',
        ),
        migrations.RenameIndex(
            model_name='workflowcollaborator',
            new_name='workflow_co_workflo_62b71d_idx',
            old_name='workflows_workflowcollaborator_instance_comment_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowcollaborator',
            new_name='workflow_co_user_id_02ebf0_idx',
            old_name='workflows_workflowcollaborator_user_notify_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowcomment',
            new_name='workflow_co_workflo_2ebb2b_idx',
            old_name='workflows_workflowcomment_instance_created_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowcomment',
            new_name='workflow_co_step_in_c3dcaa_idx',
            old_name='workflows_workflowcomment_step_created_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowcomment',
            new_name='workflow_co_author__d83563_idx',
            old_name='workflows_workflowcomment_author_created_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowcomment',
            new_name='workflow_co_is_dele_186ce2_idx',
            old_name='workflows_workflowcomment_deleted_internal_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowroleassignment',
            new_name='workflow_ro_user_id_8f49b5_idx',
            old_name='workflows_workflowroleassignment_user_active_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowroleassignment',
            new_name='workflow_ro_role_ac391f_idx',
            old_name='workflows_workflowroleassignment_role_active_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowroleassignment',
            new_name='workflow_ro_workflo_7a9bec_idx',
            old_name='workflows_workflowroleassignment_instance_role_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowroleassignment',
            new_name='workflow_ro_workflo_29bdf4_idx',
            old_name='workflows_workflowroleassignment_template_role_idx',
        ),
        migrations.AlterUniqueTogether(
            name='workflowcollaborator',
            unique_together={('workflow_instance', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='workflowroleassignment',
            unique_together={('user', 'role', 'workflow_instance'), ('user', 'role', 'workflow_template')},
        ),
        migrations.AlterUniqueTogether(
            name='workflowtemplateversion',
            unique_together={('workflow_template', 'version_number')},
        ),
    ]
