# Generated by Django 5.2.4 on 2025-08-06 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workflows', '0005_remove_workflowcollaborator_unique_workflow_collaborator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowinstance',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
