# Generated by Django 5.2.4 on 2025-10-10 19:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfringementCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_name', models.CharField(max_length=255)),
                ('case_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active Analysis'), ('review', 'Under Review'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('analysis_type', models.CharField(choices=[('literal', 'Literal Infringement'), ('doe', 'Doctrine of Equivalents'), ('induced', 'Induced Infringement'), ('contributory', 'Contributory Infringement'), ('willful', 'Willful Infringement')], default='literal', max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], default='medium', max_length=20)),
                ('patent_number', models.CharField(max_length=100)),
                ('patent_title', models.CharField(max_length=500)),
                ('patent_abstract', models.TextField(blank=True)),
                ('patent_url', models.URLField(blank=True)),
                ('accused_product_name', models.CharField(max_length=255)),
                ('accused_product_description', models.TextField()),
                ('accused_party_name', models.CharField(max_length=255)),
                ('accused_party_url', models.URLField(blank=True)),
                ('infringement_likelihood', models.IntegerField(default=50, help_text='Likelihood of infringement (0-100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('confidence_level', models.IntegerField(default=50, help_text='Confidence in analysis (0-100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('analysis_date', models.DateField(blank=True, null=True)),
                ('discovery_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_confidential', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyst', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infringement_cases_analyzed', to=settings.AUTH_USER_MODEL)),
                ('assigned_attorney', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infringement_cases_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infringement_cases_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('evidence_type', models.CharField(choices=[('product_doc', 'Product Documentation'), ('patent_doc', 'Patent Documentation'), ('technical_spec', 'Technical Specifications'), ('marketing', 'Marketing Materials'), ('source_code', 'Source Code'), ('screenshot', 'Screenshot'), ('photo', 'Photograph'), ('video', 'Video'), ('testimony', 'Expert Testimony'), ('research', 'Research Paper'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='infringement/evidence/')),
                ('url', models.URLField(blank=True)),
                ('relevance_score', models.IntegerField(default=5, help_text='Relevance score (0-10)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('related_claims', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('date_obtained', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='infringement.infringementcase')),
            ],
            options={
                'verbose_name_plural': 'Evidence',
                'ordering': ['-relevance_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_number', models.CharField(max_length=50)),
                ('claim_text', models.TextField()),
                ('claim_type', models.CharField(default='independent', max_length=50)),
                ('product_feature', models.CharField(max_length=255)),
                ('product_feature_description', models.TextField()),
                ('mapping_type', models.CharField(choices=[('literal', 'Literal Match'), ('equivalent', 'Equivalent'), ('similar', 'Similar'), ('no_match', 'No Match')], max_length=20)),
                ('match_confidence', models.IntegerField(default=50, help_text='Confidence in mapping (0-100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('analysis_notes', models.TextField(blank=True)),
                ('limitations_met', models.BooleanField(default=False)),
                ('evidence_references', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_mappings', to='infringement.infringementcase')),
            ],
            options={
                'ordering': ['claim_number'],
            },
        ),
        migrations.CreateModel(
            name='InfringementReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('preliminary', 'Preliminary Analysis'), ('detailed', 'Detailed Analysis'), ('claim_chart', 'Claim Chart'), ('risk_assessment', 'Risk Assessment'), ('executive_summary', 'Executive Summary')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('final', 'Final'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('findings', models.TextField(blank=True)),
                ('conclusion', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='infringement/reports/')),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='infringement.infringementcase')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_factor', models.CharField(choices=[('technical', 'Technical Merit'), ('legal', 'Legal Precedent'), ('financial', 'Financial Impact'), ('strategic', 'Strategic Importance'), ('validity', 'Patent Validity'), ('enforceability', 'Patent Enforceability')], max_length=20)),
                ('risk_score', models.IntegerField(help_text='Risk score (0-10, where 10 is highest risk)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('description', models.TextField()),
                ('mitigation_strategy', models.TextField(blank=True)),
                ('estimated_damages_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('estimated_damages_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('litigation_cost_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('assessed_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='infringement.infringementcase')),
            ],
            options={
                'ordering': ['-risk_score', '-assessed_date'],
            },
        ),
        migrations.AddIndex(
            model_name='infringementcase',
            index=models.Index(fields=['status', 'risk_level'], name='infringemen_status_34ff10_idx'),
        ),
        migrations.AddIndex(
            model_name='infringementcase',
            index=models.Index(fields=['patent_number'], name='infringemen_patent__7d67de_idx'),
        ),
        migrations.AddIndex(
            model_name='infringementcase',
            index=models.Index(fields=['accused_party_name'], name='infringemen_accused_46216e_idx'),
        ),
        migrations.AddIndex(
            model_name='infringementcase',
            index=models.Index(fields=['-created_at'], name='infringemen_created_453bbf_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['case', 'evidence_type'], name='infringemen_case_id_351b37_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['-relevance_score'], name='infringemen_relevan_c15750_idx'),
        ),
        migrations.AddIndex(
            model_name='claimmapping',
            index=models.Index(fields=['case', 'claim_number'], name='infringemen_case_id_77ea72_idx'),
        ),
        migrations.AddIndex(
            model_name='claimmapping',
            index=models.Index(fields=['mapping_type'], name='infringemen_mapping_f0b9bb_idx'),
        ),
        migrations.AddIndex(
            model_name='infringementreport',
            index=models.Index(fields=['case', 'report_type'], name='infringemen_case_id_a18a4d_idx'),
        ),
        migrations.AddIndex(
            model_name='infringementreport',
            index=models.Index(fields=['status'], name='infringemen_status_06f4eb_idx'),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['case', 'risk_factor'], name='infringemen_case_id_5f5762_idx'),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['-risk_score'], name='infringemen_risk_sc_8e6d23_idx'),
        ),
    ]
