# Generated by Django 5.2.4 on 2026-01-25 18:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infringement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('element_order', models.PositiveIntegerField()),
                ('element_text', models.TextField()),
                ('element_type', models.CharField(choices=[('preamble', 'Preamble'), ('body', 'Body Element'), ('transition', 'Transition')], default='body', max_length=20)),
                ('accused_feature', models.TextField(blank=True)),
                ('accused_feature_description', models.TextField(blank=True)),
                ('meets_limitation', models.BooleanField(help_text='True=Met, False=Not Met, Null=Unknown', null=True)),
                ('analysis_notes', models.TextField(blank=True)),
                ('doe_function', models.TextField(blank=True, help_text='What function does it perform?')),
                ('doe_way', models.TextField(blank=True, help_text='How does it perform the function?')),
                ('doe_result', models.TextField(blank=True, help_text='What result does it achieve?')),
                ('doe_score', models.PositiveIntegerField(blank=True, help_text='DoE similarity score (0-100)', null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='infringement.claimmapping')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['claim_mapping', 'element_order'],
                'indexes': [models.Index(fields=['claim_mapping', 'element_order'], name='infringemen_claim_m_5d93c3_idx'), models.Index(fields=['meets_limitation'], name='infringemen_meets_l_5628f9_idx')],
                'unique_together': {('claim_mapping', 'element_order')},
            },
        ),
        migrations.CreateModel(
            name='DamagesAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('damages_theory', models.CharField(choices=[('lost_profits', 'Lost Profits'), ('reasonable_royalty', 'Reasonable Royalty'), ('hybrid', 'Hybrid Approach')], default='reasonable_royalty', max_length=20)),
                ('market_size', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('accused_product_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('accused_product_units', models.PositiveIntegerField(blank=True, null=True)),
                ('profit_margin_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lost_profits_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('but_for_analysis', models.TextField(blank=True, help_text='What would have happened without infringement')),
                ('royalty_base', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('royalty_rate_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comparable_licenses', models.JSONField(blank=True, default=list)),
                ('gp_factors', models.JSONField(blank=True, default=dict)),
                ('is_willful', models.BooleanField(default=False)),
                ('willfulness_multiplier', models.DecimalField(decimal_places=1, default=1.0, max_digits=3)),
                ('willfulness_justification', models.TextField(blank=True)),
                ('estimated_damages_low', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('estimated_damages_high', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('analysis_date', models.DateField(blank=True, null=True)),
                ('assumptions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='damages_analysis', to='infringement.infringementcase')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['case'], name='infringemen_case_id_4a6a46_idx'), models.Index(fields=['damages_theory'], name='infringemen_damages_70e805_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExpertOpinion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expert_name', models.CharField(max_length=200)),
                ('expert_title', models.CharField(blank=True, max_length=200)),
                ('expert_organization', models.CharField(blank=True, max_length=200)),
                ('qualifications', models.TextField()),
                ('opinion_type', models.CharField(choices=[('technical', 'Technical Expert'), ('damages', 'Damages Expert'), ('industry', 'Industry Expert')], max_length=20)),
                ('methodology', models.TextField()),
                ('findings', models.TextField()),
                ('conclusion', models.TextField()),
                ('declaration_file', models.FileField(blank=True, null=True, upload_to='infringement/expert_declarations/')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='infringement/expert_cvs/')),
                ('is_under_protective_order', models.BooleanField(default=False)),
                ('opinion_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_opinions', to='infringement.infringementcase')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supports_claims', models.ManyToManyField(blank=True, related_name='supporting_opinions', to='infringement.claimmapping')),
            ],
            options={
                'ordering': ['-opinion_date'],
                'indexes': [models.Index(fields=['case'], name='infringemen_case_id_6f91e3_idx'), models.Index(fields=['opinion_type'], name='infringemen_opinion_a33a5b_idx')],
            },
        ),
        migrations.CreateModel(
            name='LitigationStrategy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_construction_position', models.TextField(blank=True)),
                ('key_claim_terms', models.JSONField(blank=True, default=list)),
                ('anticipated_defenses', models.JSONField(blank=True, default=list)),
                ('invalidity_risks', models.TextField(blank=True)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('opportunities', models.JSONField(blank=True, default=list)),
                ('threats', models.JSONField(blank=True, default=list)),
                ('trial_strategy', models.TextField(blank=True)),
                ('settlement_range_low', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('settlement_range_high', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('settlement_considerations', models.TextField(blank=True)),
                ('estimated_litigation_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='litigation_strategy', to='infringement.infringementcase')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['case'], name='infringemen_case_id_63e6bf_idx')],
            },
        ),
    ]
