# Generated by Django 5.2.4 on 2026-02-07 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infringement', '0002_add_comprehensive_infringement_models'),
        ('patents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infringementcase',
            name='patent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infringement_cases', to='patents.patent'),
        ),
    ]
