# Generated by Django 5.2.4 on 2026-02-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infringement', '0003_add_patent_fk_to_infringement_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infringementcase',
            name='accused_product_description',
            field=models.TextField(blank=True),
        ),
    ]
