# Generated by Django 5.2.4 on 2026-05-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infringement', '0004_alter_infringementcase_accused_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimelement',
            name='evidence_references',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='claimelement',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claimelement',
            name='review_status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('ai_draft', 'AI Draft'), ('edited', 'Edited')], default='confirmed', max_length=20),
        ),
        migrations.AddField(
            model_name='claimmapping',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claimmapping',
            name='review_status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('ai_draft', 'AI Draft'), ('edited', 'Edited')], default='confirmed', max_length=20),
        ),
    ]
