# Generated by Django 5.2.4 on 2026-05-29 15:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infringement', '0005_claimelement_evidence_references_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceScreenshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='infringement/screenshots/%Y/%m/')),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('bbox_x', models.FloatField(default=0)),
                ('bbox_y', models.FloatField(default=0)),
                ('bbox_width', models.FloatField(default=0)),
                ('bbox_height', models.FloatField(default=0)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='infringement.infringementcase')),
                ('claim_elements', models.ManyToManyField(blank=True, help_text='Claim limitations this screenshot is evidence for', related_name='screenshots', to='infringement.claimelement')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(help_text='Source PDF the region was captured from', on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='infringement.evidence')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['case'], name='infringemen_case_id_8a5935_idx'), models.Index(fields=['evidence'], name='infringemen_evidenc_3f8917_idx')],
            },
        ),
    ]
