# Generated by Django 5.2.4 on 2026-05-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infringement', '0006_evidencescreenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencescreenshot',
            name='annotations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
