# Generated by Django 5.2.4 on 2026-05-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infringement', '0007_evidencescreenshot_annotations'),
    ]

    operations = [
        migrations.AddField(
            model_name='infringementcase',
            name='claim_term_colors',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
