# Generated by Django 5.2.4 on 2026-05-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infringement', '0008_infringementcase_claim_term_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='infringementcase',
            name='claim_term_excluded',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
